# Generated by Django 3.2.4 on 2022-11-22 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='profileimages/profile-avatar.png', upload_to='profileimages/'),
        ),
    ]
